export const PERMISSIONS = [
  "CAN_SELL",
  "CAN_MANAGE_INVENTORY",
  "CAN_MANAGE_USERS",
  "CAN_VIEW_REPORTS",
  "CAN_MANAGE_CUSTOMERS",
  "CAN_MANAGE_STORES",
  "CAN_MANAGE_ZONES",
  "CAN_MANAGE_TARIFFS",
] as const;
