import z from "zod";

export const PERMISSIONS = [
  // Partner Orders
  "CAN_LIST_PARTNER_ORDERS",
  "CAN_LIST_ALL_PARTNER_ORDERS",
  "CAN_VIEW_PARTNER_ORDERS",
  "CAN_CREATE_PARTNER_ORDERS",
  "CAN_EDIT_PARTNER_ORDERS",
  "CAN_DELETE_PARTNER_ORDERS",

  // HQ Orders
  "CAN_LIST_HQ_ORDERS",
  "CAN_LIST_ALL_HQ_ORDERS",
  "CAN_VIEW_HQ_ORDERS",
  "CAN_CREATE_HQ_ORDERS",
  "CAN_EDIT_HQ_ORDERS",
  "CAN_DELETE_HQ_ORDERS",

  // Customers
  "CAN_LIST_CUSTOMERS",
  "CAN_LIST_ALL_CUSTOMERS",
  "CAN_VIEW_CUSTOMERS",
  "CAN_CREATE_CUSTOMERS",
  "CAN_EDIT_CUSTOMERS",
  "CAN_DELETE_CUSTOMERS",
  "CAN_PROVISION_CUSTOMER_ACCESS",

  // Users
  "CAN_LIST_USERS",
  "CAN_VIEW_USERS",
  "CAN_CREATE_USERS",
  "CAN_EDIT_USERS",
  "CAN_DELETE_USERS",

  // Stores
  "CAN_LIST_STORES",
  "CAN_VIEW_STORES",
  "CAN_CREATE_STORES",
  "CAN_EDIT_STORES",
  "CAN_DELETE_STORES",

  // Boxes
  "CAN_LIST_BOXES",
  "CAN_VIEW_BOXES",
  "CAN_CREATE_BOXES",
  "CAN_EDIT_BOXES",
  "CAN_DELETE_BOXES",
  "CAN_SELL_BOXES",
  "CAN_LIST_BOX_SALES",

  // Warehouse
  "CAN_LIST_PACKAGES",
  "CAN_VIEW_PACKAGES",
  "CAN_VIEW_PACKAGE_RECEIPT",
  "CAN_CREATE_PACKAGES",
  "CAN_EDIT_PACKAGES",
  "CAN_DELETE_PACKAGES",
  "CAN_VIEW_OWN_PACKAGES",

  // Shipping
  "CAN_LIST_SHIPMENTS",
  "CAN_FULFILL_SHIPMENTS",
  "CAN_VIEW_SHIPMENT_RATES",
  "CAN_SELECT_SHIPMENT_PROVIDER",
  "CAN_VIEW_SHIPMENT_LABEL",
  "CAN_CANCEL_SHIPMENTS",

  // Tariffs
  "CAN_LIST_TARIFFS",
  "CAN_VIEW_TARIFFS",
  "CAN_CREATE_TARIFFS",
  "CAN_EDIT_TARIFFS",
  "CAN_DELETE_TARIFFS",

  // Zones
  "CAN_LIST_ZONES",
  "CAN_VIEW_ZONES",
  "CAN_CREATE_ZONES",
  "CAN_EDIT_ZONES",
  "CAN_DELETE_ZONES",

  // Settings
  "CAN_VIEW_SETTINGS",
  "CAN_EDIT_SETTINGS",

  // Reports
  "CAN_VIEW_REPORTS",
] as const;

export const userRoleSchema = z.object({
  name: z.string(),
  permissions: z.array(z.enum(PERMISSIONS)),
});

export type Permission = z.infer<
  typeof userRoleSchema.shape.permissions.element
>;

export type UserRolePrimitives = z.infer<typeof userRoleSchema>;
